### PR TITLE
Updated d3.js to latest version

### PR DESCRIPTION
**Pull request by thaerlabs**

### CODE REVIEW

**Comment by robinboehm** [comment]
Sorry, didn't saw this.
We should change the module and "unwrap" d3 and use it via global variable.
Serving this via DI in a fix version is an anti-pattern.

@thaerlabs You want to do this job? ;)

**Comment by thaerlabs** [comment]
No, I'm sorry

**Comment by robinboehm** [comment]
ok, no prob :)

**Comment by enanox** [comment]
If you are interested, here Ari Lerner has a good workaround for using the last D3 version (note that the one hosted at d3js.org corresponds to the last release) [ng-newsletter](http://www.ng-newsletter.com/posts/d3-on-angular.html)

**Comment by robinboehm** [comment]
Why he highly recommend to wrap it in a service?

**Comment by enanox** [comment]
IMHO, to avoid polluting the global scope. Second, to benefit from DI and in the example he uses the async loading to return a promise when the lib was loaded. I think that it's possible to generate a provider as you currently have, wrapping the global d3 object, and adding the possibility to add more custom methods (idk, take for example d3_horizon() helper).

**Pull request closed without merging**
